version: "3.9"

services:
  nextjs-frontend:
    image: anishs1207/nft-marketplace:latest
    read_only: true
    networks:
      - frontend
    ports:
      - 3000:3000
    init: true
    environment:
      - NODE_ENV: production
    restart: unless-stopped

networks: frontend
